name: 'Re-usable Infrastructure Workflow'
on:
  workflow_call:
    inputs:
      scope:
        description: 'Turbo Repo scope to run the build for'
        required: false
        type: string
      stack-output-path:
        description: 'The path where CDKTF outputs the terraform json'
        required: false
        type: string
      raw-terraform:
        description: 'Whether or not this service uses raw terraform'
        required: false
        default: false
        type: boolean
    outputs:
      terraform-output:
        description: "The output of terraform apply"
        value: ${{ jobs.apply.outputs.terraform-output }}

permissions:
  pull-requests: write   # Allow Terraform Comment to write to PRs
  contents: read  # This is required for actions/checkout
  id-token: write  # Access the Github JWT for AWS access

jobs:

    plan:
      # Only run this job on a pull request event
      if: github.event_name == 'pull_request'
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        # Get the AWS credentials
        - name: AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-region: us-east-1
            role-to-assume: arn:aws:iam::996905175585:role/PocketGHAReadOnlyRole
        - name: Execute CDKTF
          if: inputs.raw-terraform == false
          uses: pocket/pocket-monorepo/.github/actions/cdktf@main
          with:
            stack-output-path: ${{inputs['stack-output-path']}}
            scope: ${{inputs['scope']}}
            environment: production
            behavior: plan
            github-token: ${{ secrets.GITHUB_TOKEN }}
            pagerduty-token: ${{ secrets.PAGERDUTY_TOKEN }}
            terraform-token: ${{ secrets.TERRAFORM_TOKEN }}

        - name: Execute Raw Terraform
          if: inputs.raw-terraform == true
          uses: pocket/pocket-monorepo/.github/actions/raw-terraform@main
          with:
            stack-output-path: ${{inputs['stack-output-path']}}
            scope: ${{inputs['scope']}}
            environment: production
            behavior: plan
            github-token: ${{ secrets.GITHUB_TOKEN }}
            pagerduty-token: ${{ secrets.PAGERDUTY_TOKEN }}
            terraform-token: ${{ secrets.TERRAFORM_TOKEN }}

    apply:
      if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'
      runs-on: ubuntu-latest
      outputs:
        terraform-output: ${{ steps.set_output.outputs.terraform-output }}
      steps:        
        - name: Checkout
          uses: actions/checkout@v4
        - name: Development AWS Credentials
          if: github.ref == 'refs/heads/dev'
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-region: us-east-1
            role-to-assume: arn:aws:iam::410318598490:role/PocketGHARole
        - name: Production AWS Credentials
          if: github.ref == 'refs/heads/main' 
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-region: us-east-1
            role-to-assume: arn:aws:iam::996905175585:role/PocketGHARole
        - name: Execute Development CDKTF
          if: inputs.raw-terraform == false && github.ref == 'refs/heads/dev'
          uses: pocket/pocket-monorepo/.github/actions/cdktf@main
          with:
            stack-output-path: ${{inputs['stack-output-path']}}
            scope: ${{inputs['scope']}}
            environment: development
            behavior: apply
            github-token: ${{ secrets.GITHUB_TOKEN }}
            pagerduty-token: ${{ secrets.PAGERDUTY_TOKEN }}
            terraform-token: ${{ secrets.TERRAFORM_TOKEN }}
        - name: Execute Developement Raw Terraform
          if: inputs.raw-terraform == true && github.ref == 'refs/heads/dev'
          uses: pocket/pocket-monorepo/.github/actions/raw-terraform@main
          with:
            stack-output-path: ${{inputs['stack-output-path']}}
            scope: ${{inputs['scope']}}
            environment: development
            behavior: apply
            github-token: ${{ secrets.GITHUB_TOKEN }}
            pagerduty-token: ${{ secrets.PAGERDUTY_TOKEN }}
            terraform-token: ${{ secrets.TERRAFORM_TOKEN }}

        - name: Execute Production CDKTF
          if: inputs.raw-terraform == false && github.ref == 'refs/heads/main'
          uses: pocket/pocket-monorepo/.github/actions/cdktf@main
          with:
            stack-output-path: ${{inputs['stack-output-path']}}
            scope: ${{inputs['scope']}}
            environment: production
            behavior: apply
            github-token: ${{ secrets.GITHUB_TOKEN }}
            pagerduty-token: ${{ secrets.PAGERDUTY_TOKEN }}
            terraform-token: ${{ secrets.TERRAFORM_TOKEN }}

        - name: Execute Production Raw Terraform
          if: inputs.raw-terraform == true && github.ref == 'refs/heads/main'
          uses: pocket/pocket-monorepo/.github/actions/raw-terraform@main
          with:
            stack-output-path: ${{inputs['stack-output-path']}}
            scope: ${{inputs['scope']}}
            environment: production
            behavior: apply
            github-token: ${{ secrets.GITHUB_TOKEN }}
            pagerduty-token: ${{ secrets.PAGERDUTY_TOKEN }}
            terraform-token: ${{ secrets.TERRAFORM_TOKEN }}

        - name: Set terraform output
          id: set_output
          run: |
            echo "Grabbing Terraform Output"
            cd ${{inputs['stack-output-path']}}
            echo "terraform-output=$(terraform output -json | jq -c)" >> $GITHUB_OUTPUT
    